version: '2'

services:
  infinispan1:
    image: jboss/infinispan-server:8.2.4.Final
    container_name: ispn-1
  infinispan2:
    image: jboss/infinispan-server:8.2.4.Final
    container_name: ispn-2
  sparkMaster:
    image: gustavonalle/spark:2.0.0
    container_name: sparkMaster
    volumes:
      - ./recommend-mllib/target:/usr/local/code
  sparkSlave:
    image: gustavonalle/spark:2.0.0
    container_name: sparkSlave
    links:
      - sparkMaster:master
  recommend-service:
    build:
      context: ./recommend-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
