{
    "kind": "Template",
    "apiVersion": "v1",
    "metadata": {
        "name": "spark-recommend-poc",
        "creationTimestamp": null,
        "annotations": {
            "description": "Spark MLLib JDG Demo",
            "tags": "quickstart,nodejs,mongodb",
            "iconClass": "icon-nodejs"
        }
    },
    "objects": [{
        "kind": "Service",
        "apiVersion": "v1",
        "metadata": {
            "name": "${RECOMMEND_SERVICE_NAME}",
            "creationTimestamp": null
        },
        "spec": {
            "ports": [ {
                "name": "app-mongodb",
                "port": 27017,
                "targetPort": 27017
            },{
                "name": "app-web-ui",
                "port": 9000,
                "targetPort": 9000

            },
             {
                "name": "app-infispan-hotrod",
                "port": 11222,
                "targetPort": 11222
            }],
            "selector": {
                "name": "${RECOMMEND_SERVICE_NAME}"
            },
            "portalIP": "",
            "type": "ClusterIP",
            "sessionAffinity": "None"
        },
        "status": {
            "loadBalancer": {}
        }
    }, {
        "kind": "DeploymentConfig",
        "apiVersion": "v1",
        "metadata": {
            "name": "${RECOMMEND_SERVICE_NAME}",
            "creationTimestamp": null
        },
        "spec": {
            "strategy": {
                "type": "Recreate"
            },
            "replicas": 1,
            "selector": {
                "name": "${RECOMMEND_SERVICE_NAME}"
            },
            "template": {
                "metadata": {
                    "creationTimestamp": null,
                    "labels": {
                        "name": "${RECOMMEND_SERVICE_NAME}"
                    }
                },
                "spec": {
                    "containers": [{
                      "name": "infinispan-jdg-server",
                      "image": "docker.io/jboss/infinispan-server:8.2.3.Final",
                      "ports": [{
                        "containerPort": 11222
                      }]

                    }, {
                        "name": "recommend-rest-api",
                        "image": "docker.io/metadatapoc/recommend-service",
                        "env": [{
                            "name": "MONGODB_USER",
                            "value": "admin"
                        }, {
                            "name": "MONGODB_PASSWORD",
                            "value": "admin"
                        }, {
                            "name": "MONGODB_DATABASE",
                            "value": "recommend-service"
                        }, {
                            "name": "MONGODB_ADMIN_PASSWORD",
                            "value": "admin"
                        }],
                        "ports": [{
                            "containerPort": 9000
                        }]
                    }, {
                            "name": "recommend-database",
                            "image": "docker.io/centos/mongodb-32-centos7",
                            "env": [{
                                "name": "MONGODB_USER",
                                "value": "admin"
                            }, {
                                "name": "MONGODB_PASSWORD",
                                "value": "admin"
                            }, {
                                "name": "MONGODB_DATABASE",
                                "value": "recommend-service"
                            }, {
                                "name": "MONGODB_ADMIN_PASSWORD",
                                "value": "admin"
                            }],
                            "ports": [{
                                "containerPort": 27017
                            }]
                        }
                    ]
                }
            }
        }
    }],
    "parameters": [{
        "name": "RECOMMEND_SERVICE_NAME",
        "displayName": "recommend Service Name",
        "required": true,
        "value": "recommend-service"
    }, {
        "name": "DATABASE_USER",
        "displayName": "MongoDB Username",
        "description": "Username for MongoDB user that will be used for accessing the database.",
        "generate": "expression",
        "from": "user[A-Z0-9]{3}"
    }, {
        "name": "DATABASE_PASSWORD",
        "displayName": "MongoDB Password",
        "description": "Password for the MongoDB user.",
        "generate": "expression",
        "from": "[a-zA-Z0-9]{16}"
    }, {
        "name": "DATABASE_NAME",
        "displayName": "Database Name",
        "value": "recommend-service"
    }, {
        "name": "DATABASE_ADMIN_PASSWORD",
        "displayName": "Database Administrator Password",
        "description": "Password for the database admin user.",
        "generate": "expression",
        "from": "[a-zA-Z0-9]{16}"
    }, {
        "name": "MEMORY_LIMIT",
        "displayName": "Memory Limit",
        "description": "Maximum amount of memory the container can use.",
        "value": "512Mi"
    }, {
        "name": "MEMORY_MONGODB_LIMIT",
        "displayName": "Memory Limit",
        "description": "Maximum amount of memory the container can use.",
        "value": "512Mi"
    }, {
        "name": "NAMESPACE",
        "displayName": "Namespace",
        "description": "The OpenShift Namespace where the ImageStream resides.",
        "value": "openshift"
    }],
    "message": "You can connect to the database using MongoDB connection URL mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${DATABASE_SERVICE_NAME}/${MONGODB_DATABASE}"
}
